### ISSUE TITLE
使用douban   helm 安装后 archery应用一直会连127.0.0.1:3306 

### ISSUE THREAD

**Issue by smallhorsegg** [douban/charts#30]
[2022-08-16 17:52:13,551][MainThread:140275747579712][task_id:default][config.py:33][ERROR]- 获取系统配置信息失败:(2003, "Can't connect to MySQL server on '127.0.0.1' (111)")Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)

values.yaml中只改了mysql/redis的密码

```
# subcharts redis
redis:
  embedded: true
  # url: "redis://127.0.0.1:6379/0"
  # urlSecret: ""
  # urlSecretKey: "CACHE_URL"
  # dingdingUrl: "redis://127.0.0.1:6379/1"
  # dingdingUrlSecret: ""
  # dingdingUrlSecretKey: "DINGDING_CACHE_URL"
  # embedded 为 false, 会使用外部的 redis, 下方的 redis 就不会生效
  architecture: standalone
  auth:
    password: "GowpY9ssdasd98IjedP"
  master:
    persistence:
      enabled: false
      size: 8Gi
      # storageClass: ""

# subcharts mysql
mysql:
  embedded: true
  # url: "mysql://root:@127.0.0.1:3306/archery"
  # urlSecret: ""
  # urlSecretKey: "DATABASE_URL"
  # embedded 为 false时, 会使用外部的 mysql, 下方的 mysql 配置不会生效
  architecture: standalone
  auth:
    database: archery
    rootPassword: "Gssss98IjedP"
```

**Comment by LeoQuote** [comment]
你能描述一下你是如何装的, 完整的values 文件吗?

**Comment by LeoQuote** [comment]
你可以尝试一下更新一下 archery 的版本 

```
image:
  repository: hhyo/archery
  tag: latest
  pullPolicy: IfNotPresent
```
tag 可以更新到最新的 latest
