### ISSUE TITLE
codecov: Failed to upload report from CI

### ISSUE THREAD

**Issue by naesheim** [douban/charts#58]
Hi, and thanks for the effort in making a chart for codecov.

I'm currently facing this error when running the codecov-action@v3:

**Error: getaddrinfo EAI_AGAIN codecov-minio - name: Upload coverage to Codecov**

My ci config looks like:

```
        uses: codecov/codecov-action@v3
        with:
          url: codecov.mycompany.com
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: org/repo
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```

I'm running minio: embedded: false and define minio connection in codecov_config under 
setup: 
  services: 
     minio:
       host: storage.googleapis.com
